import './styles/globals.css';
import Header from './components/containers/Header';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className="bg-[#191919] text-white">
				<Header />
				<main>{children}</main>
			</body>
		</html>
	);
}
